external_components:
  - source:
      type: local
      path: components
    components: [st7121]

esphome:
  name: tab5-ha-hmi
  friendly_name: tab5-ha-hmi

esp32:                                                                                                                                                                                                                                     
    variant: esp32p4                                                                                                                                                                                                                         
    flash_size: 16MB                                                                                                                                                                                                                         
    cpu_frequency: 360MHz                                                                                                                                                                                                                    
    engineering_sample: true                                                                                                                                                                                                                 
    framework:                                                                                                                                                                                                                               
      type: esp-idf                                                                                                                                                                                                                          
      advanced:                                                                                                                                                                                                                              
        enable_idf_experimental_features: true       
        

esp32_hosted:
  variant: esp32c6
  active_high: true
  clk_pin: GPIO12
  cmd_pin: GPIO13
  d0_pin: GPIO11
  d1_pin: GPIO10
  d2_pin: GPIO9
  d3_pin: GPIO8
  reset_pin: GPIO15
  slot: 1

logger:
  hardware_uart: USB_SERIAL_JTAG

psram:
  mode: hex
  speed: 200MHz

api:
ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

i2c:
  - id: bsp_bus
    sda: GPIO31
    scl: GPIO32
    frequency: 400kHz

pi4ioe5v6408:
  - id: pi4ioe1
    address: 0x43
  - id: pi4ioe2
    address: 0x44

switch:
  - platform: gpio
    id: wifi_power
    pin:
      pi4ioe5v6408: pi4ioe2
      number: 0
    restore_mode: ALWAYS_ON
  - platform: gpio
    id: usb_5v_power
    pin:
      pi4ioe5v6408: pi4ioe2
      number: 3
    restore_mode: ALWAYS_ON
  - platform: gpio
    id: external_5v_power
    pin:
      pi4ioe5v6408: pi4ioe1
      number: 2
    restore_mode: ALWAYS_ON
    

esp_ldo:
  - voltage: 2.5V
    channel: 3

output:
  - platform: ledc
    pin: GPIO22
    id: backlight_pwm
    frequency: 1000Hz

light:
  - platform: monochromatic
    output: backlight_pwm
    name: "Display Backlight"
    id: backlight
    restore_mode: RESTORE_DEFAULT_ON

display:
  - platform: st7121
    id: lcd
    dimensions:
      width: 720
      height: 1280
    color_order: RGB
    reset_pin:
      pi4ioe5v6408: pi4ioe1
      number: 4
    rotation: 90
    pixel_mode: 16bit
    auto_clear_enabled: false
    update_interval: 1s
    lambda: |-
      it.filled_rectangle(0, 0, it.get_width(), it.get_height(), Color(0, 255, 0));
